// Generated by tools/gen_pixel_atlas.py with docs/pixel_atlas.json. Do not edit.
#pragma once
#include <stddef.h>
#include "UiLayoutGeometry.h"
namespace VqeafAtlas {
struct Region {const char *name; VqeafLayout::Rect rect; const char *token;};
struct Screen {const char *id; const char *name; const Region *regions; size_t count;};
extern const Screen screens[16];
extern const size_t screenCount;
const Screen *get(const char *id);
}
