#!/usr/bin/env python3
"""Generate BOUNDED RGB565-compatible glyph bitmaps, not distributable font files.

Bitmap shapes are derived from the system's DejaVu Sans family. The committed
C++ array is small and requires no TTF engine, heap allocation or filesystem.
Regenerate only when the source font is installed and its license is respected.
"""
from pathlib import Path
import unicodedata
from PIL import Image,ImageDraw,ImageFont
root=Path(__file__).resolve().parents[1]
fontdir=Path('/usr/share/fonts/truetype/dejavu')
fonts=[(fontdir/'DejaVuSans.ttf',10,12),(fontdir/'DejaVuSans-Bold.ttf',13,16)]
base='aăâeêioôơuưyAĂÂEÊIOÔƠUƯY'
tones=['','\u0300','\u0301','\u0309','\u0303','\u0323']
letters={ord(unicodedata.normalize('NFC', b+t)) for b in base for t in tones}
letters.update(ord(c) for c in 'đĐ')
codepoints=sorted(set(range(32,127))|letters)
lines=['// AUTO-GENERATED by tools/generate_vietnamese_glyphs.py','// UTF-8 NFC glyph subset for Vietnamese + printable ASCII. See docs/FONT_ICONS_V23.md.', '#pragma once','#include <Arduino.h>','#include <TFT_eSPI.h>','#include <stdint.h>','namespace UiVietnameseFont {','struct Glyph { uint16_t cp; uint8_t advance; uint16_t rows[18]; };']
for idx,(file,size,baseline) in enumerate(fonts):
    f=ImageFont.truetype(str(file),size)
    lines.append(f'static const Glyph glyphs{idx}[] = {{')
    for cp in codepoints:
        ch=chr(cp)
        width=min(16, max(1,round(f.getlength(ch))))
        im=Image.new('1',(16,18),0);ImageDraw.Draw(im).text((0,baseline),ch,font=f,anchor='ls',fill=1,stroke_width=0)
        rows=[]
        for y in range(18):
            bits=0
            for x in range(16):
                if im.getpixel((x,y)):bits|=1<<x
            rows.append('0x%04X'%bits)
        lines.append(f'{{0x{cp:04X}, {width}, {{{", ".join(rows)}}}}},')
    lines.append('};')
lines.append(r'''
inline bool hasUtf8(const char *s) { for(;s&&*s;++s)if((uint8_t)*s>=128)return true;return false; }
inline const Glyph *lookup(uint16_t cp,uint8_t role) {
  const Glyph *g=role==1?glyphs1:glyphs0;
  const size_t n=role==1?sizeof(glyphs1)/sizeof(Glyph):sizeof(glyphs0)/sizeof(Glyph);
  size_t lo=0,hi=n;
  while(lo<hi){size_t m=(lo+hi)/2;if(g[m].cp<cp)lo=m+1;else hi=m;}
  if(lo<n&&g[lo].cp==cp)return &g[lo];
  return lookupFallback(role);
}
// UTF-8 decoder: malformed/incomplete sequences consume a byte and use '?' instead
inline uint32_t next(const char *&s) {
  uint8_t a=(uint8_t)*s++;
  if(a<0x80)return a;
  uint32_t cp=0;int left=0;uint32_t lower=0;
  if((a&0xE0)==0xC0){cp=a&31;left=1;lower=0x80;}
  else if((a&0xF0)==0xE0){cp=a&15;left=2;lower=0x800;}
  else if((a&0xF8)==0xF0){cp=a&7;left=3;lower=0x10000;}
  else return '?';
  const char *p=s;
  for(int i=0;i<left;i++) {
    uint8_t b=(uint8_t)*p;if(!b||(b&0xC0)!=0x80)return '?';
    cp=(cp<<6)|(b&0x3F);++p;
  }
  s=p;
  if(cp<lower||cp>0x10FFFF||(cp>=0xD800&&cp<=0xDFFF))return '?';
  return cp;
}
inline int measure(const char *s,uint8_t role) {
  int w=0;while(s&&*s){uint32_t cp=next(s);const Glyph *g=lookup(cp>65535?'?':cp,role);w+=g->advance;}return w;
}
inline int draw(TFT_eSPI &tft,int x,int y,const char *s,uint16_t fg,uint16_t bg,uint8_t role,int clipW=240) {
  const int start=x;int drawn=0;
  // One opaque background region prevents stale glyphs during focused redraws.
  const int count=measure(s,role);tft.fillRect(x,y,min(clipW,count),role==1?18:15,bg);
  while(s&&*s){uint32_t cp=next(s);const Glyph *g=lookup(cp>65535?'?':cp,role);
    if(x+g->advance>start+clipW)break;
    for(int yy=0;yy<18;++yy){uint16_t bits=g->rows[yy];int xx=0;
      while(bits){while(xx<16 && !(bits & (1u<<xx)))++xx;
        if(xx>=16)break;
        const int first=xx;
        while(xx<16 && (bits & (1u<<xx)))++xx;
        tft.drawFastHLine(x+first,y+yy,xx-first,fg);
        if(xx>=16)break;
      }
    }
    x+=g->advance;++drawn;
  }
  return x-start;
}
} // UiVietnameseFont
'''.replace('inline const Glyph *lookup(uint16_t cp,uint8_t role) {','inline const Glyph *lookupFallback(uint8_t role) {\n  const Glyph *g=role==1?glyphs1:glyphs0;\n  const size_t n=role==1?sizeof(glyphs1)/sizeof(Glyph):sizeof(glyphs0)/sizeof(Glyph);\n  for(size_t i=0;i<n;++i)if(g[i].cp==\'?\')return &g[i];return g;\n}\ninline const Glyph *lookup(uint16_t cp,uint8_t role) {'))
target=root/'src/core/UiVietnameseFont.h';content='\n'.join(lines)+'\n'
content=content.replace("for(size_t i=0;i<n;++i)if(g[i].cp=='?')return &g[i];return g;","for(size_t i=0;i<n;++i){if(g[i].cp=='?')return &g[i];}\n  return g;")
target.write_text(content,encoding='utf-8')
print('Generated',len(codepoints),'NFC glyphs ×2',target.stat().st_size,'bytes of source')
